name = "FluxProjects"
uuid = "3312eaee-3c3c-41f2-8dbe-05ec6247947c"
authors = ["Francososa <franky.sosa@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"

[compat]
Pluto = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
